import { DM_Sans } from "next/font/google";
import "../../globals.css";
import HeaderDashboard from "@/app/components/HeaderDashboard";

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // los pesos que vas a usar
  variable: '--font-dm-sans',    // nombre de la variable CSS (opcional)
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${dmSans.variable} antialiased`}>
      <body>
        <HeaderDashboard sistema="Novedades" />
        {children}
      </body>
    </html>
  );
}
