import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import HeaderDashboard from "../../components/HeaderDashboard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function GySLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderDashboard sistema="GyS" />
        {children}
      </body>
    </html>
  );
}
