name: Novedades Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 143.198.105.146 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh gys_user@143.198.105.146 << 'EOF'
            cd ~/var/www/novedades-prod || {
              git clone https://github.com/seguroweb/novedades.git ~/var/www/novedades-prod
              cd ~/var/www/novedades-prod
            }
            git pull origin main
            npm install
            npm build
            pm2 restart novedades-prod || pm2 start npm --name "novedades-prod" -- start
          EOF
